<a href="https://colab.research.google.com/github/davidofitaly/neural_network/blob/main/02_basics/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

####Scalar

In [ ]:
scalar = 3

print(scalar)
print(type(scalar))

3
<class 'int'>


In [ ]:
scalar = 3.0

print(scalar)
print(type(scalar))

3.0
<class 'float'>


####Vector

In [ ]:
vector = np.array([2,4,-6,5])

print(vector)
print(type(vector))
print(f'Shape: {vector.shape}')
print(f'Row: {vector.ndim}')
print(f'Length: {len(vector)}')


[ 2  4 -6  5]
<class 'numpy.ndarray'>
Shape: (4,)
Row: 1
Length: 4


In [ ]:
vector = np.array([2,4,-6,5,], dtype='float')
print(vector)
print(f'Type: {vector.dtype}')

[ 2.  4. -6.  5.]
Type: float64


####Matrix

In [ ]:
array = np.array([[2,6,3],
                  [5,-3,4]])

print(array)
print(type(array))
print(f'Shape: {array.shape}')
print(f'Row: {array.ndim}')
print(f'Type: {array.dtype}')
print(f'Length: {len(array)}')

[[ 2  6  3]
 [ 5 -3  4]]
<class 'numpy.ndarray'>
Shape: (2, 3)
Row: 2
Type: int64
Length: 2


In [ ]:
array = np.array([[2,6,4],
                  [5,4,5],
                  [4,2,1]], dtype='float')

print(array)
print(type(array))
print(f'Shape: {array.shape}')
print(f'Row: {array.ndim}')
print(f'Type: {array.dtype}')
print(f'Length: {len(array)}')

[[2. 6. 4.]
 [5. 4. 5.]
 [4. 2. 1.]]
<class 'numpy.ndarray'>
Shape: (3, 3)
Row: 2
Type: float64
Length: 3


#####Tensor

In [ ]:
tensor = np.array([[[1,2,3],
                   [4,5,6]],
                   [[7,8,9],
                    [3,7,3]]

                  ])

print(tensor)
print(type(tensor))
print(f'Shape: {tensor.shape}')
print(f'Row: {tensor.ndim}')
print(f'Type: {tensor.dtype}')
print(f'Length: {len(tensor)}')

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]]
<class 'numpy.ndarray'>
Shape: (2, 2, 3)
Row: 3
Type: int64
Length: 2


In [ ]:

tensor = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [3, 7, 3]],
    [[2, 3, 5],
     [7, 2, 5]]
])

print(tensor)
print(type(tensor))
print(f'Rozmiar macierzy: {tensor.shape}')
print(f'Typ danych macierzy: {tensor.dtype}')
print(f'Rząd: {tensor.ndim}')
print(f'Długosc: {len(tensor)}')


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]

 [[2 3 5]
  [7 2 5]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (3, 2, 3)
Typ danych macierzy: int64
Rząd: 3
Długosc: 3


In [ ]:
tensor = np.array([
    [[1, 2, 3, 4],
     [4, 5, 6, 4],
     [4, 2, 5, 2]],
    [[7, 8, 9, 8],
     [3, 7, 3, 9],
     [5, 2, 4, 3]],
    [[2, 3, 5, 4],
     [7, 2, 5, 1],
     [8, 2, 7, 2]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]]
])

print(tensor)
print(type(tensor))
print(f'Rozmiar macierzy: {tensor.shape}')
print(f'Typ danych macierzy: {tensor.dtype}')
print(f'Rząd: {tensor.ndim}')
print(f'Długosc: {len(tensor)}')


[[[1 2 3 4]
  [4 5 6 4]
  [4 2 5 2]]

 [[7 8 9 8]
  [3 7 3 9]
  [5 2 4 3]]

 [[2 3 5 4]
  [7 2 5 1]
  [8 2 7 2]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (5, 3, 4)
Typ danych macierzy: int64
Rząd: 3
Długosc: 5
