<a href="https://colab.research.google.com/github/davidofitaly/neural_network/blob/main/02_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Import of libraries

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

###Function Relu

In [12]:
def max_relu(x):
    return max(x, 0.0)

In [13]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [14]:
data = np.random.randn(50)
data = sorted(data)
data

[-2.2581291780016146,
 -1.677123799421746,
 -1.4808474044901778,
 -1.1849498629744948,
 -1.1108481505115158,
 -1.0520459188471936,
 -0.9847815871596941,
 -0.9090223856667279,
 -0.8544405895831944,
 -0.7938551635759078,
 -0.7658448427006683,
 -0.6621948730630973,
 -0.6577739467880213,
 -0.5951980569300608,
 -0.5593525100486363,
 -0.5488668153646628,
 -0.5311234421492604,
 -0.49620872610198413,
 -0.4884966321272522,
 -0.477000431882913,
 -0.3574449650546709,
 -0.3333901128487913,
 -0.2006112807712331,
 -0.20056310253236348,
 -0.18732295859082917,
 -0.06948941178196542,
 -0.003793674536207469,
 0.057011670134082204,
 0.0880613413009692,
 0.13963471151795498,
 0.16868401071149736,
 0.2762769399680482,
 0.3033719788912553,
 0.30816838770721533,
 0.3862640030827002,
 0.9131231290194776,
 0.9309878498034273,
 0.9345358925406124,
 0.9418700547293818,
 1.028264258644016,
 1.0340374556359258,
 1.1248294659339764,
 1.2183887194762362,
 1.3518364223624069,
 1.409714717410648,
 1.4380061025785755,


In [15]:
max_relu_data = np.array([max_relu(x) for x in data])

max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.057012, 0.088061, 0.139635,
       0.168684, 0.276277, 0.303372, 0.308168, 0.386264, 0.913123,
       0.930988, 0.934536, 0.94187 , 1.028264, 1.034037, 1.124829,
       1.218389, 1.351836, 1.409715, 1.438006, 1.455176, 1.511659,
       2.049569, 2.82701 ])

In [16]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.258129            0.0
1 -1.677124            0.0
2 -1.480847            0.0
3 -1.184950            0.0
4 -1.110848            0.0

In [17]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='Relu function')

###Sigmoid


In [18]:
def sigmoid(x):
    return 1/ (1 + np.exp(-x))

In [19]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [20]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-7.140099986980644,
 -5.561772368432038,
 -5.248219167758901,
 -4.301660884673867,
 -3.993565484084608,
 -3.44101480159867,
 -3.4387338789112407,
 -3.290204275476789,
 -2.9736090113555402,
 -2.78852418178578,
 -2.719916390671633,
 -2.317123054065018,
 -2.1545562773743874,
 -2.103736792884143,
 -2.0805896431701347,
 -1.9824885885424066,
 -1.8866648239928017,
 -1.7432976251940557,
 -1.6191403972850287,
 -1.6172496964287002,
 -1.5326722652519742,
 -0.7584745322038788,
 -0.7490004497544003,
 0.3584208606355004,
 0.5049535911608412,
 0.5774880117216111,
 0.6572503831924466,
 0.9209089799243841,
 1.1265252067268843,
 1.1427494175025559,
 1.3807074375283022,
 1.4753158372240454,
 1.6615169044491784,
 1.9571938281047925,
 2.353771220408508,
 2.380399832851652,
 2.7703902604587034,
 3.0401869554000966,
 3.0415239564225036,
 3.431077970050422,
 3.5420854805560316,
 3.8513240299370524,
 3.8673806726113513,
 4.2766314095046685,
 4.386541374513543,
 4.404046402049298,
 4.666209541094872,
 4.863095

In [21]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.0007920450029821507,
 0.003827256817922261,
 0.005229381487548566,
 0.013364999067401582,
 0.018100214119778506,
 0.031037949883276877,
 0.031106621136127086,
 0.0359087733314691,
 0.04863247132276152,
 0.057947467000874484,
 0.06180831442760152,
 0.08971473083354424,
 0.10390622314093671,
 0.10873415489180138,
 0.11099776898921263,
 0.12105380281700508,
 0.1316252119767897,
 0.14889455905731783,
 0.1653234540302984,
 0.16558452000248186,
 0.177603037869763,
 0.3189775533661272,
 0.3210391368150147,
 0.5886581152711621,
 0.6236227353977628,
 0.6404891932735998,
 0.6586424549695414,
 0.7152272804173192,
 0.7551970683714152,
 0.7581840776696127,
 0.7991045937845915,
 0.8138640228252614,
 0.8404415243513024,
 0.8762289392483557,
 0.9132335178054485,
 0.9153204300366361,
 0.9410546383239724,
 0.9543569736360711,
 0.954415177687447,
 0.9686618072666184,
 0.9718617986608369,
 0.9791906514624131,
 0.9795153216936249,
 0.9863009008956646,
 0.9877092493734851,
 0.9879199507330184,
 0.9906798

In [22]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -7.140100      0.000792
1 -5.561772      0.003827
2 -5.248219      0.005229
3 -4.301661      0.013365
4 -3.993565      0.018100

In [23]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

###Tanh

In [24]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [25]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-4.87640638367783,
 -4.392658539958266,
 -3.9718154097682032,
 -3.952621039219369,
 -3.4865112312911166,
 -3.1952295524315493,
 -2.839637090365438,
 -2.73632949932819,
 -2.5148956022459177,
 -2.445951165720103,
 -2.349284545931417,
 -2.2031520343958464,
 -2.196827857861104,
 -2.1837546084128237,
 -2.1386204676186114,
 -2.1243705529358055,
 -2.0816124813790133,
 -2.009995067703053,
 -1.9041131716803747,
 -1.806249391729324,
 -1.7953890730771795,
 -1.7746035951866628,
 -1.750251238545834,
 -1.7082395389470273,
 -1.669430634551506,
 -1.6537405878482316,
 -1.57408429431168,
 -1.568917877618902,
 -1.4424850388021004,
 -1.3749318776746262,
 -1.2435049729240812,
 -1.2216372537570959,
 -1.0141847344851993,
 -0.7753103781873237,
 -0.5518301899847305,
 -0.49563174198410576,
 -0.4501820692376554,
 -0.44779279327585025,
 -0.4108338679679623,
 -0.33917318798786905,
 -0.26134698273977525,
 -0.2581888455854061,
 -0.21569725512920995,
 -0.1260061727917826,
 0.10985325754165338,
 0.13743036949084744,


In [26]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.999883744908433,
 -0.9996941215784823,
 -0.9992904208367731,
 -0.9992626616166942,
 -0.9981281193543234,
 -0.9966506467275351,
 -0.993191185224466,
 -0.9916350345250985,
 -0.9870046399669028,
 -0.9850976184088388,
 -0.9819478228152531,
 -0.9758937286884422,
 -0.975590632529463,
 -0.974952094673007,
 -0.9726182680431651,
 -0.9718378132956152,
 -0.9693620337870006,
 -0.964726977504834,
 -0.9565882049170149,
 -0.9474493745703724,
 -0.9463264224246044,
 -0.944111798009606,
 -0.9414041257209032,
 -0.9364311933236271,
 -0.9314763680393491,
 -0.9293691384446803,
 -0.9176729968214081,
 -0.9168534640402466,
 -0.8941968668268547,
 -0.8798113095571359,
 -0.8464522734181511,
 -0.8401364707293834,
 -0.7674873213098715,
 -0.6500067405183158,
 -0.501890644186914,
 -0.45867482368527607,
 -0.4220486548902257,
 -0.42008299045209635,
 -0.3891804788709461,
 -0.32673905156353794,
 -0.2555549789248196,
 -0.25260071999372774,
 -0.21241323078828847,
 -0.12534349117543286,
 0.10941348678453915,
 0.13657163

In [27]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -4.876406  -0.999884
1 -4.392659  -0.999694
2 -3.971815  -0.999290
3 -3.952621  -0.999263
4 -3.486511  -0.998128

In [28]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

###Softmax Function

In [29]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [30]:
data = np.random.randn(4, 5)
data

array([[ 0.449646,  0.12374 , -0.543701,  0.618633,  0.374407],
       [-1.446002,  0.373008, -0.92971 ,  0.276444,  0.675999],
       [ 2.031298,  0.59832 , -0.835787,  0.73717 ,  1.54647 ],
       [-0.649206, -1.722072,  0.118856,  1.282496,  0.748767]])

In [31]:
result = softmax(data)
result

array([[0.237878, 0.171718, 0.088095, 0.281673, 0.220637],
       [0.043884, 0.270575, 0.07354 , 0.245669, 0.366332],
       [0.457582, 0.109178, 0.02602 , 0.12544 , 0.28178 ],
       [0.069224, 0.023676, 0.149218, 0.477732, 0.280149]])

In [34]:
result.sum(axis=1)

array([1., 1., 1., 1.])