<a href="https://colab.research.google.com/github/davidofitaly/neural_network/blob/main/03_keras/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Import of libraries

In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px

tf.__version__

'2.17.0'

###First model

In [10]:
from tensorflow.keras.models import Sequential


model = Sequential()
print(model)

<Sequential name=sequential_1, built=False>


In [12]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 4)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.add(Dense(units=2))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

###Activaiton function

In [15]:
from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})

data.head()


data    linear
0 -3.507426 -3.507426
1 -3.225191 -3.225191
2 -2.139934 -2.139934
3 -2.063813 -2.063813
4 -1.779344 -1.779344

In [16]:
px.line(data, x='data', y='linear', width=800, range_y=[-2,2])

In [17]:
from tensorflow.keras.activations import sigmoid

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})

data.head()

data   sigmoid
0 -2.795465  0.057570
1 -2.714103  0.062146
2 -2.568495  0.071194
3 -2.444218  0.079862
4 -2.325687  0.089018

In [18]:
px.line(data, x='data', y='sigmoid', width=800, range_y=[0,1])

In [19]:
from tensorflow.keras.activations import relu

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})

data.head()

data  relu
0 -2.941899   0.0
1 -2.852129   0.0
2 -2.422920   0.0
3 -2.357491   0.0
4 -2.100131   0.0

In [20]:
px.line(data, x='data', y='relu', width=800, range_y=[0,1])

In [21]:
from tensorflow.keras.activations import tanh

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})

data.head()

data      tanh
0 -2.227050 -0.977006
1 -2.198727 -0.975682
2 -2.095275 -0.970176
3 -2.004319 -0.964331
4 -1.935526 -0.959178

In [22]:
px.line(data, x='data', y='tanh', width=800, range_y=[-1.5,1.5])

In [23]:
model = Sequential()

model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

###Model compilation

In [24]:

model.compile(optimizer='rmsprop', #
              loss='binary_crossentropy',
              metrics=['accuracy']) #


model.compile(optimizer='rmsprop', #
              loss='categorical_crossentropy',
              metrics=['accuracy']) #


model.compile(optimizer='rmsprop', #
              loss='mse') #

###Model training

In [25]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

###Example - binary classification

In [27]:
data = np.random.randn(1000,150)

labels = np.random.randint(2, size=(1000,1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [28]:
data[:3]

array([[ 8.83859684e-01, -4.82896311e-01,  2.17975027e+00,
        -9.62281945e-01,  6.26504812e-01,  6.31558101e-03,
        -1.29364609e+00,  8.00915170e-01,  6.87785648e-01,
        -2.68509273e-01,  1.98631195e+00,  1.68052535e+00,
         2.22691299e-01,  1.99991266e+00,  9.77992779e-02,
         1.16798627e+00, -6.35738663e-01,  1.29042951e+00,
        -9.37003038e-03, -2.81711334e-01,  1.68672676e+00,
         1.31685188e+00, -5.80128567e-01, -6.22044512e-01,
        -6.90141565e-01,  3.15381735e+00,  5.10179572e-02,
        -1.55731946e+00, -1.69637135e+00, -5.36050271e-01,
        -7.21482629e-01, -1.03082060e+00,  6.18179781e-02,
         2.12222206e-01, -8.19221417e-01,  2.19948520e-01,
        -2.98707164e-01, -7.51954219e-01, -3.56759523e-01,
        -5.35428234e-01, -9.71794363e-01,  3.31386564e-01,
        -1.14730483e+00,  1.07941344e+00,  4.35419561e-01,
         2.37644430e-01,  3.97510461e-01,  5.00101590e-01,
        -5.39156852e-01,  1.39147454e+00, -1.89585065e+0

In [29]:
labels[:10]

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0]])

In [32]:
model = Sequential()

model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4543 - loss: 0.8562   
Epoch 2/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5470 - loss: 0.7282 
Epoch 3/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5715 - loss: 0.6930 
Epoch 4/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6646 - loss: 0.6178 
Epoch 5/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6799 - loss: 0.6028 
Epoch 6/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7037 - loss: 0.5701
Epoch 7/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7624 - loss: 0.5346
Epoch 8/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7958 - loss: 0.5003
Epoch 9/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8348 - loss: 0.4773
Epoch 10/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8192 - loss: 0.4572
Epoch 11/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.4485
Epoch 12/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.86

In [34]:
model = Sequential()

model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)



Epoch 1/20


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5060 - loss: 0.8170   
Epoch 2/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5657 - loss: 0.7105
Epoch 3/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6152 - loss: 0.6486
Epoch 4/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6892 - loss: 0.5842
Epoch 5/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7121 - loss: 0.5735
Epoch 6/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7450 - loss: 0.5347
Epoch 7/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7745 - loss: 0.5026
Epoch 8/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8119 - loss: 0.4802
Epoch 9/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8043 - loss: 0.4552
Epoch 10/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8513 - loss: 0.4163
Epoch 11/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8464 - loss: 0.4205
Epoch 12/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8800 - loss: 0.38

In [36]:
model = Sequential()

model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.4924 - loss: 0.8422 - val_accuracy: 0.4400 - val_loss: 0.8382
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5457 - loss: 0.7193 - val_accuracy: 0.4350 - val_loss: 0.8206
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5945 - loss: 0.6626 - val_accuracy: 0.4500 - val_loss: 0.8098
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6482 - loss: 0.6139 - val_accuracy: 0.4550 - val_loss: 0.8090
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7144 - loss: 0.5684 - val_accuracy: 0.4600 - val_loss: 0.8098
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7646 - loss: 0.5245 - val_accuracy: 0.4750 - val_loss: 0.8126
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7941 - loss: 0.5034 - val_accuracy: 0.4900 - val_loss: 0.8200
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8230 - loss: 0.4692 - val_accuracy: 0.5000 - val_loss: 0.8269
Ep

In [39]:
model = Sequential()

model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



In [42]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [43]:
model = Sequential()

model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)


Epoch 1/20


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5308 - loss: 0.8538 - val_accuracy: 0.5050 - val_loss: 0.8147
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5437 - loss: 0.7305 - val_accuracy: 0.4950 - val_loss: 0.7947
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6039 - loss: 0.6574 - val_accuracy: 0.5200 - val_loss: 0.7853
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6509 - loss: 0.6171 - val_accuracy: 0.5050 - val_loss: 0.7839
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7023 - loss: 0.5700 - val_accuracy: 0.5100 - val_loss: 0.7851
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7663 - loss: 0.5324 - val_accuracy: 0.5150 - val_loss: 0.7896
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7741 - loss: 0.5141 - val_accuracy: 0.5200 - val_loss: 0.7960
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8057 - loss: 0.4780 - val_accuracy: 0.5150 - val_loss: 0.8051
Epo

In [44]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [45]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[0.42735738],
       [0.7950977 ],
       [0.15327932],
       [0.34152773],
       [0.19717948]], dtype=float32)

In [46]:
model.predict_proba(test_data)

AttributeError: 'Sequential' object has no attribute 'predict_proba'

In [51]:

probabilities = model.predict(test_data)


classes = (probabilities > 0.5).astype("int32")
classes

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[0],
       [1],
       [0],
       [0],
       [0]], dtype=int32)

###Example - multi-class classification

In [52]:
data = np.random.random((1000, 150))
labels = np.random.randint(10, size=(1000, 1))

In [53]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [54]:
data[:3]

array([[0.65933691, 0.94973831, 0.1866041 , 0.58792569, 0.37556247,
        0.8880093 , 0.09455854, 0.96452328, 0.73591276, 0.73486031,
        0.22636295, 0.2436525 , 0.32295223, 0.50013947, 0.90582299,
        0.77056612, 0.1701903 , 0.68751523, 0.33720514, 0.58053596,
        0.499522  , 0.99496821, 0.303532  , 0.03873955, 0.92361613,
        0.1123115 , 0.63854187, 0.90108914, 0.24332562, 0.05464649,
        0.74542124, 0.17729393, 0.4875425 , 0.41980254, 0.98131972,
        0.18397748, 0.993696  , 0.58095646, 0.39422346, 0.71667442,
        0.65819302, 0.08188382, 0.17165309, 0.57869158, 0.79533666,
        0.15549207, 0.1226795 , 0.94905049, 0.19397325, 0.30793754,
        0.00554398, 0.80390505, 0.20449215, 0.6571259 , 0.5678557 ,
        0.78859767, 0.24710495, 0.31439779, 0.42378772, 0.04811988,
        0.67880327, 0.36305408, 0.46887876, 0.04017784, 0.08324562,
        0.26034416, 0.48794475, 0.26277701, 0.43860586, 0.86493906,
        0.30686563, 0.43101296, 0.25671481, 0.55

In [55]:
labels[:10]

array([[9],
       [5],
       [1],
       [1],
       [8],
       [2],
       [2],
       [3],
       [6],
       [1]])

In [56]:
from tensorflow.keras.utils import to_categorical

labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [57]:
labels[1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [58]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.0994 - loss: 2.4979 - val_accuracy: 0.0600 - val_loss: 2.3844
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1038 - loss: 2.3436 - val_accuracy: 0.0650 - val_loss: 2.3714
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1294 - loss: 2.3018 - val_accuracy: 0.0900 - val_loss: 2.3787
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1438 - loss: 2.2899 - val_accuracy: 0.0800 - val_loss: 2.3738
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1631 - loss: 2.2825 - val_accuracy: 0.0750 - val_loss: 2.3738
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1509 - loss: 2.2728 - val_accuracy: 0.0900 - val_loss: 2.3722
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1799 - loss: 2.2759 - val_accuracy: 0.0900 - val_loss: 2.3808
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2043 - loss: 2.2374 - val_accuracy: 0.1100 - val_loss: 2.3797
Ep

In [59]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[0.05133191, 0.02676557, 0.31163254, 0.05119172, 0.07011239,
        0.06560519, 0.09486675, 0.14350736, 0.05554933, 0.12943734],
       [0.07114828, 0.05255695, 0.07979421, 0.06492963, 0.09165414,
        0.12352966, 0.06255471, 0.13728927, 0.18119359, 0.13534954],
       [0.07834195, 0.1263055 , 0.09139713, 0.07774067, 0.09262682,
        0.11035097, 0.12490135, 0.13588078, 0.04637264, 0.11608215],
       [0.03662372, 0.08279045, 0.17064221, 0.15725702, 0.15938646,
        0.0368039 , 0.06259691, 0.06557694, 0.140665  , 0.08765745],
       [0.22951294, 0.07069313, 0.05724055, 0.0819444 , 0.04752948,
        0.17638734, 0.09522831, 0.07909296, 0.0873633 , 0.07500758],
       [0.12140564, 0.21449181, 0.09333993, 0.08803882, 0.08776799,
        0.05727502, 0.16239233, 0.06273825, 0.07718953, 0.0353606 ],
       [0.20429452, 0.04640013, 0.14108948, 0.04156311, 0.03330422,
        0.07981596, 0.10696006, 0.08750178, 0.07912351, 0.1799472 ],
       [0.10991153, 0.0525465 , 0.0691481

In [60]:
probabilities = model.predict(test_data)


classes = np.argmax(probabilities, axis=1)
classes

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([2, 8, 7, 2, 0, 1, 0, 7, 2, 6])

###Example - regression

In [62]:
data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

In [63]:
data[:3]

array([[1.03430744e-02, 3.04375665e-01, 9.75674448e-01, 4.30503417e-01,
        6.53869809e-01, 2.79899104e-01, 6.07841192e-01, 1.10593039e-01,
        1.31874298e-01, 1.74584882e-01, 8.75786537e-01, 5.08527380e-01,
        6.16669775e-02, 2.33660216e-01, 1.98579053e-01, 4.53768706e-02,
        1.31968857e-01, 7.56200907e-01, 9.34698142e-02, 4.07393094e-02,
        2.58883463e-01, 4.03396774e-01, 3.22722234e-01, 3.70657143e-01,
        9.58808125e-01, 9.61498550e-01, 9.08613316e-01, 3.50781836e-01,
        1.33758495e-01, 2.79555292e-01, 8.91982702e-01, 7.34302998e-01,
        8.02129793e-01, 9.49568043e-02, 7.08071829e-01, 2.73844837e-01,
        7.30152044e-01, 8.03866499e-01, 6.10554209e-01, 8.69847857e-01,
        7.82570444e-01, 1.64396244e-01, 6.01805721e-01, 3.53915876e-01,
        6.06924353e-02, 2.93216540e-01, 8.64043219e-01, 4.00343337e-01,
        5.19913292e-01, 3.60460190e-01, 2.51498009e-01, 7.63383657e-01,
        2.26238436e-01, 8.56045889e-01, 5.92297632e-01, 6.469142

In [64]:
labels[:10]

array([ 4.06507032, 40.18395398, 39.91584908,  1.3682327 ,  3.79487307,
       16.47227585, 24.54038425,  5.00935072, 12.36194379, 33.36846073])

In [65]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 702.2445 - val_loss: 440.1204
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 408.6120 - val_loss: 273.3684
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 259.1965 - val_loss: 203.6759
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 208.5763 - val_loss: 197.7595
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 198.0247 - val_loss: 197.7350
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 192.7732 - val_loss: 197.6216
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 202.8745 - val_loss: 197.9871
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 199.1242 - val_loss: 200.1290
Epoch 9/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 198.8719 - val_loss: 199.6169
Epoch 10/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 203.2121 - val_loss: 197.6777
Epoch 11/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 196.2629 - val_loss: 197.9553
Epoch 12/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s

In [67]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 21.5374 - mse: 650.2164 - val_loss: 15.6538 - val_mse: 369.7215
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.0166 - mse: 329.3556 - val_loss: 12.6222 - val_mse: 220.9880
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.0996 - mse: 201.2152 - val_loss: 12.1738 - val_mse: 197.6305
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5648 - mse: 187.1243 - val_loss: 12.2151 - val_mse: 199.4911
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.9586 - mse: 198.0290 - val_loss: 12.2284 - val_mse: 200.2507
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.9105 - mse: 197.6228 - val_loss: 12.1748 - val_mse: 197.7955
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.9792 - mse: 195.6432 - val_loss: 12.1632 - val_mse: 197.4839
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.3808 - mse: 206.1091 - val_loss: 12.1659 - val_mse: 197.6585
Epoch 9/30
25/25 ━━━━━━━